### ISSUE TITLE
new remote branch vs. pull request

### ISSUE THREAD

**Issue by mportesdev** [oldcompcz/readme#3]
Mam pripravenou testovaci branch s opravou preklepu v readme, ale nevim jaky je dalsi postup. Pull requesty zatim uplne nechapu, na strance "Compare changes" je tlacitko "Create pull request" neaktivni.

Pushnout branch nemuzu, nemam prava.

```
$ git checkout typos
Switched to branch 'typos'
$ git push -u origin HEAD
remote: Permission to oldcompcz/readme.git denied to myrmica-habilis.
fatal: unable to access 'https://github.com/oldcompcz/readme/': The requested URL returned error: 403
```

Jak spravne na to?

**Comment by berk76** [comment]
Ahoj,

pull-requesty se dají dělat několika způsoby podle toho zda máš práva ve vzdáleném repozitáři zapisovat a vytvářet větve nebo ne.

1. pokud máš práva zápisu, tak se to dělá tak jak si popsal - vytvoří se nová feature větev a v ní úprava a nakonec se udělá pull request obvykle proti master větvi

1. pokud ale právo zápisu do vzdáleného reopzitáře nemáš, tak si uděláš fork repozitáře k sobě (fork je vpravo nahoře vedle star) Úpravu uděláš do svého forku a github ti tam začne nabízet pull request do původního repozitáře ze kterého si forkoval.

Právo na readme jsem ti přidal :slightly_smiling_face:

**Comment by mportesdev** [comment]
Ahoj, diky za rychlou odpoved. Vetev jsem nahral na remote a vytvoril pull request.

**Comment by berk76** [comment]
Díky za spolupráci. :+1:
